[View in Colaboratory](https://colab.research.google.com/github/divyanshujhawar/MachineLearning/blob/master/Untitled.ipynb)

In [0]:
import plotly
# To store data
import pandas as pd

# To do linear algebra
import numpy as np

# To create plots
from matplotlib.colors import rgb2hex
from matplotlib.cm import get_cmap
import matplotlib.pyplot as plt

# To create nicer plots
import seaborn as sns

# To create interactive plots
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)

# To get new datatypes
from collections import Counter

# To investigate distributions
from scipy.stats import norm, skew, probplot

# To build models
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

#from lightgbm import LGBMClassifier

# To measure time
from time import time

In [0]:
col_names = ['Ph1', 'Ph2', 'Ir1', 'Fo1', 'Fo2', 'Di3', 'Di4', 'Ph3', 'Ph4', 'Ph5', 'Ph6', 'Co1', 'Co2', 'Co3', 'So1', 'So2', 'Di1', 'Di2', 'Te1', 'Fo3', 'Resident1', 'Resident2']
house = pd.read_csv("house1.csv", names=col_names, header=None, delimiter=r"\s+")

In [0]:
house.head()

,Ph1,Ph2,Ir1,Fo1,Fo2,Di3,Di4,Ph3,Ph4,Ph5,...,Co2,Co3,So1,So2,Di1,Di2,Te1,Fo3,Resident1,Resident2
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17

In [0]:
house.describe(include='all').round(3)

,Ph1,Ph2,Ir1,Fo1,Fo2,Di3,Di4,Ph3,Ph4,Ph5,...,Co2,Co3,So1,So2,Di1,Di2,Te1,Fo3,Resident1,Resident2
count,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,...,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000,2592000.000
mean,0.003,0.001,0.003,0.415,0.153,0.112,0.093,0.006,0.001,0.001,...,0.047,0.006,0.006,0.030,0.003,0.028,0.053,0.197,11.211,7.128
std,0.058,0.026,0.058,0.493,0.360,0.315,0.290,0.076,0.024,0.027,...,0.212,0.075,0.078,0.172,0.056,0.165,0.224,0.398,5.698,6.140
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1.000
25%,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,11.000,2.000
50%,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,11.000,2.000
75%,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,14.000,11.000
max,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,27.000,27.000

In [0]:
#Histograms on their counts
%matplotlib inline

import matplotlib.pyplot as plot
house.hist(bins=50,figsize=(20,15))
#save_fig("attribute_hou_plots")
plot.show()

In [0]:
with sns.plotting_context("notebook",font_scale=2.5):
    g = sns.pairplot(house[['Resident1','Resident2','Ph1']],hue="Ph1", palette='tab20',size=6)
    g.set(xticklabels=[]);

In [0]:
import plotly

from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)

house_copy = house.copy()

label1 = house_copy.pop('Resident1')
label2 = house_copy.pop('Resident2')

In [0]:

#For Resident1
label_counts = label2.value_counts()

n = label_counts.shape[0]
colormap = get_cmap('viridis')
colors = [rgb2hex(colormap(col)) for col in np.arange(0, 1.01, 1/(n-1))]

data = go.Bar(x = label_counts.index,
              y = label_counts,
              marker = dict(color = colors))

layout = go.Layout(title = 'Resident1 Activity Label Distribution',
                   xaxis = dict(title = 'Activity'),
                   yaxis = dict(title = 'Count'))

fig = go.Figure(data=[data], layout=layout)
iplot(fig)

In [0]:
#For Resident2
label_counts = label2.value_counts()

n = label_counts.shape[0]
colormap = get_cmap('viridis')
colors = [rgb2hex(colormap(col)) for col in np.arange(0, 1.01, 1/(n-1))]

data = go.Bar(x = label_counts.index,
              y = label_counts,
              marker = dict(color = colors))

layout = go.Layout(title = 'Resident2 Activity Label Distribution',
                   xaxis = dict(title = 'Activity'),
                   yaxis = dict(title = 'Count'))

fig = go.Figure(data=[data], layout=layout)
iplot(fig)

In [0]:
house

,Ph1,Ph2,Ir1,Fo1,Fo2,Di3,Di4,Ph3,Ph4,Ph5,Ph6,Co1,Co2,Co3,So1,So2,Di1,Di2,Te1,Fo3
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591970,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591971,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591972,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591973,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591974,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591975,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591976,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591977,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591978,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591979,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591980,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591981,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591982,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591983,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591984,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591985,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591986,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591987,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591988,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591989,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591990,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591991,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591992,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591993,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591994,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591995,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591996,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591997,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591998,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2591999,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [0]:
tsne_data = house.copy()

scl = StandardScaler()
tsne_data = scl.fit_transform(tsne_data)

pca = PCA(n_components=0.9, random_state=3)
tsne_data = pca.fit_transform(tsne_data)


tsne = TSNE(random_state=3)
tsne_transformed = tsne.fit_transform(tsne_data)


# Create subplots
fig, axarr = plt.subplots(2, 1, figsize=(3,2))


### Plot Activities
# Get colors
n = label2.unique().shape[0]
colormap = get_cmap('viridis')
colors = [rgb2hex(colormap(col)) for col in np.arange(0, 1.01, 1/(n-1))]

for i, group in enumerate(label_counts.index):
    # Mask to separate sets
    mask = (label2==group).values
    axarr[0].scatter(x=tsne_transformed[mask][:,0], y=tsne_transformed[mask][:,1], c=colors[i], alpha=0.5, label2=group)

axarr[0].set_title('TSNE Activity Visualisation')
axarr[0].legend()


### Plot Subjects
# Get colors
n = subject_data.unique().shape[0]
colormap = get_cmap('nipy_spectral')
colors = [rgb2hex(colormap(col)) for col in np.arange(0, 1.01, 1/(n-1))]

for i, group in enumerate(subject_data.unique()):
    # Mask to separate sets
    mask = (subject_data==group).values
    axarr[1].scatter(x=tsne_transformed[mask][:,0], y=tsne_transformed[mask][:,1], c=colors[i], alpha=0.5, label2=group)

axarr[1].set_title('TSNE Subject Visualisation')
plt.show()